### ISSUE TITLE
Euchre: Don't always protect the left

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#105]
From a player:

> Protecting the left. Why. The bot just cost my team a euchre doing that by not throwing trump on offsuit. And the bots don't lead highest trump either only if they have a bower.

**Comment by antross** [comment]
I think the refinement here is likely along the lines of protecting the left *until* your team has taken a trick (or if your team has already taken two tricks). 

The real value of protecting the left is that it's almost a guaranteed trick if protected, typically for ensuring the makers don't take all five tricks. If we've already taken a trick, then our goal is to Euchre the makers so we should shift strategies to avoid giving up an easy trick. 

That said, if we already took two tricks, then being more cautious to get the third for the Euchre is warranted again.
