### ISSUE TITLE
Chat: Inexplicable '****' messages

### ISSUE THREAD

**Issue by johnbent** [TricksterCards/TricksterBots#111]
Sometimes someone's chat message will show up as '****' and they haven't used vulgarity and they aren't blocked or unfriended or anything else which might explain why their message was replaced with '****'

**Comment by johnson520** [comment]
This is a Trickster Cards issue, not a bot issue.

There are some strings that will set off the filter even if they are not full words or not particularly profane.

**Comment by johnbent** [comment]
Thanks @johnson520. Is there a way to create issues for trickster cards?
