### ISSUE TITLE
Bridge: Customer wonders why partner leading trumps

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#114]
> In this hand, why is my partner leading trumps to me? I led him a heart and he has the ace. The dummy only has one heart left. Play the heart now for a sure trick!
> 
> Thank you for listening.

% PBN ---------------------------
[Event "Trickster Cards: Practice Bridge"]
[Date "2023.05.27"]
[West "Patricia"]
[North "Loretta"]
[East "Abraham"]
[South "Skipper John"]
[Dealer "E"]
[Vulnerable "NS"]
[Deal "E:AKJ97.J642.74.A2 T854.5.AKQJ9.QT4 Q63.Q9.T853.KJ83 2.AKT873.62.9765"]
[Declarer "E"]
[Contract "2S"]
[Auction "E"]
1S 2D 2S Pass
Pass Pass
[Play "S"]
H5 H9 HK H2
- - S2 S7

**Comment by antross** [comment]
The bot led trump because it was their last (to ensure they could pull a trump from both dummy and declarer's hands at the same time, reducing their ability to ruff later). This is correct per our discussions with Bridge instructors.
