### ISSUE TITLE
500: Feedback about bot going NT without the "bird"

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#131]
Can you please please please stop the damn computer going no trumps without the bird, it'll be successful about 2% of the time. It's making more stupid 7/8 calls and losing track of what's best too often....

**Comment by johnson520** [comment]
Perhaps related:

> I humbly suggest you either fix how the bot plays no-trumps. Or just block it from calling no-trumps.
> 
> 90% of the time it calls no-trumps, it loses the hand.

**Comment by antross** [comment]
Fixed by #189
