### ISSUE TITLE
Pitch: 10-Point: Bots bid too high without support

### ISSUE THREAD

**Issue by antross** [TricksterCards/TricksterBots#149]
Too easy for the opponents to have the A and claim both it and the 3 on the first trick.

**Comment by johnson520** [comment]
> Your bots overbid all the time. Most of the time there is no reason to bid 8 or 9. They constantly bid too high just because they hold points, but have no overcards. J,J,3 will likely not get you 9 points. Also, on call your partner, you shouldn't be able to call your own card. All of the cards should be dealt up front.
