### ISSUE TITLE
500: Add convention of bidding 6NT if holding the Joker

### ISSUE THREAD

**Issue by antross** [TricksterCards/TricksterBots#153]
Needs more info. Not sure how common it is to play with this convention and if it would apply when playing with two Jokers.

**Comment by johnson520** [comment]
>  I have been playing on trickster for 4 years, and everyone I play with makes the assumption if you bid 6n that you have the joker. Occasionally someone will say 6nt when they have aces, but their partner assumes they have the joker even though they didn't. In that case, it isn't a huge deal because they still have help with whatever they bid.
