### ISSUE TITLE
Bridge: Erroneous 4NT bid

### ISSUE THREAD

**Issue by antross** [TricksterCards/TricksterBots#155]
![image](https://github.com/TricksterCards/TricksterBots/assets/785009/ad12b4f6-a4ff-4184-a058-4b62c20e114e)

**Comment by johnson520** [comment]
> Again bot response inappropriate. No human would bid like this

% PBN ---------------------------
[Event "Trickster Cards: Challenge Bridge"]
[Date "2023.08.30"]
[West "Kerri"]
[North "Paige"]
[East "Cassie"]
[South "Teapat"]
[Dealer "W"]
[Vulnerable "NS"]
[Deal "W:Q5.QT9843.K52.AK J984.KJ5.8643.64 A763.62.QT7.Q832 KT2.A7.AJ9.JT975"]
[Declarer "N"]
[Contract "4NT"]
[Auction "W"]
1H Pass 1S 2C
3H 4NT Pass Pass
Pass
[Play "E"]
S3 - - -

**Comment by johnson520** [comment]
> I was told to report inappropriate bot bidding immediately. No human would respond with the bots bid

% PBN ---------------------------
[Event "Trickster Cards: Challenge Bridge"]
[Date "2023.08.30"]
[West "Enoch"]
[North "Joyce"]
[East "Kendra"]
[South "Teapat"]
[Dealer "E"]
[Vulnerable "EW"]
[Deal "E:43.JT9632.AK7.K3 .Q4.J965.AJT9765 AKQ98765.A.QT3.Q JT2.K875.842.842"]
[Declarer "N"]
[Contract "5NT"]
[Auction "E"]
1H 3C Pass 5NT
Pass Pass Pass
[Play "E"]
HJ - - -
