### ISSUE TITLE
Spades: Have bot bid Nil if it would have bid 1 with 2-card pass

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#164]
> Why bot bid one on 2 card pass? If you only got one then bid nil and pass it

**Comment by antross** [comment]
We had another customer report an issue that appears to be due to this behavior over the weekend.

**Comment by antross** [comment]
Just noticed this is the same as #39. Moving comments there so we can properly track how much feedback we're getting on this (lack of) behavior.
