### ISSUE TITLE
500: Observation on bot card play

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#190]
> Not the first time I've experienced this problem. In your challenge game today 2v2 Ace High to 500, I was partnered with a Bot called Delilah. I bid nil in the first game. Delilah starts leading higher cards then continues in the same suit with much lower cards despite having high cards of other suits. So I end up playing a higher card and couldn't reach Nil. The bot repeated the same action in the 4th game. Please stop the bots from playing so stupidly.

**Comment by antross** [comment]
Looks like this was Spades feedback - not 500. Also, this doesn't appear to be the case with recent testing so closing.
