### ISSUE TITLE
500: Require *some* strength to bid 6NT

### ISSUE THREAD

**Issue by antross** [TricksterCards/TricksterBots#196]
Some folks who don't play with the convention that 6NT indicates holding the Joker are frustrated when the bot bids 6NT without a hand that stands even the slightest chance at making it.

Filing to consider balancing the two by only bidding 6NT if BOTH holding the Joker AND we have some hand strength for an NT bid (e.g.  the ability to take at least a few tricks).

**Comment by johnson520** [comment]
Related customer comment:

> Why have you changed the algorithm? The computer almost defaults to a no-trump bid every time? Not much fun
