### ISSUE TITLE
Euchre: Only retain a trump until 4th trick

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#2]
From a customer:

> Suppose it is your bid, and you take the first three tricks, and have two cards left, 9 of trump and a queen. It is your lead and you know the 9 is good. Your bot will play the queen first, followed by the 9. Proper is to play the 9 first, forcing opponents to make a choice of which card to hold for the last trick. Maybe they have to choose between two aces or two kings. It’s all about increasing your chances.

**Comment by antross** [comment]
I think this is running into logic where the bot tries to retain one trump to regain the lead if needed, but this is pointless once you're on the 4th trick. We should scope that portion of the bot logic to only apply to the 1st-3rd tricks.
