### ISSUE TITLE
Whist: Suggestion for bot improvement in NT

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#210]
> Bots need to continue to play a suit in a "no trump" game when only it and partner has cards in a suit.

**Comment by johnson520** [comment]
> You have a logic flaw in Whist when the bid is no trump. Your bots lead a Joker thinking it is the high card, but it is actually the lowest card, so the bot always loses those tricks. You probably have a similar issue when bot is not leading in not trump round and thinks it is playing a high card.

**Comment by antross** [comment]
> Whist: In bidding a "NO" If bot takes the lead, instead of playing the same suit I initially played before it got the lead, it comes back in a different suit I may not have and we get set. In all cases, it has the suit I started with in hands which, had it played the starting suit, we'd make it.

**Comment by antross** [comment]
Merged with #86
