### ISSUE TITLE
Pinochle Card Passing

### ISSUE THREAD

**Issue by RussCranberry** [TricksterCards/TricksterBots#22]
It would be good if the strategy for passing cards between the successful bidder and partner would maximize chances of Double Pinochle.

One way to do this is to pass Double Pinochle (DP) parts based on the suit that was called trump.  If trump is Spades or Diamonds the partner would attempt to pass DP parts to the bidder.  If Hearts or Clubs is trump, the bidder would pass them to their partner.

I hope I'm doing this properly.  I saw the note about the bot code being posted in Github last week.  Although I do have a programming background, I'm hoping to stay out of that level of detail if possible and leave it to the experts.

**Comment by johnson520** [comment]
A customer referred us to https://www.fgbradleys.com/rules/rules4/Pinochle%20-%20rules.pdf as a resource for what we should pass to the declarer. Here's the relevant paragraph:

> Passing cards: If your partner receives the
> bid, he will name the trump suit and you will
> pass four cards to him. Typically, you pass
> trump cards, Aces and, if your partner
> named ♠ or ♦ trump, pinochle cards. If your
> partner names ♣ or ♥ trump, never pass him
> pinochle cards — he’ll pass you back for
> pinochle. The reason is that the high bidder
> may want to empty his hand of non-trump
> suits so that when other cards are led, he can
> immediately trump those tricks.

**Comment by antross** [comment]
Thanks for the suggestion @RussCranberry!

**Comment by antross** [comment]
Also, from https://www.pagat.com/marriage/pintip.html#passingcards
> Passing Cards
> If your partner takes the bid, it is now your responsibility to select four cards to pass across the table. Your goal is to help your partner's hand as much as possible. To that end, you should send the following:
> 
> * Trump (but if one of these is a Nine of trump, and you can send an off-suit Ace instead, go for it), because these cards will enhance the chances of getting a run for your team, and because these cards will be valuable in the trick-taking phase of the game.
> * Aces out of trump, because these will strengthen the power base of your partner's hand.
> * If your partner called Spades, send the Jack of Diamonds; if Diamonds were called, send the Queen of Spades. Use your intuition and telepathy to decide whether either of these cards should take precedence over a non-trump Ace. What you're trying to do with these cards is fill in a 300 Pinochle, which can be a big boost to your team.

**Comment by antross** [comment]
Reviewing the current logic in our Pinochle bot, it looks like we already align fairly closely with the two linked references:
https://github.com/TricksterCards/TricksterBots/blob/4319805d196b6c0e52b2b1628edb19197f804fa0/TricksterBots/Bots/Pinochle/PinochleMelder.cs#L320

Specifically, the current bot will prefer passing trump, then pass Pinochle parts if partner bid Spades/Diamonds, then pass off-suit Aces. This already gives slightly higher preference to passing Pinochle parts than those two references which suggest passing off-suit Aces first. 

Given the guidance in the external references, I'm inclined to not make a change here at the moment, though I could see how some players may prefer aiming for a Double Pinochle before all else. Perhaps something to consider if we ever allow players to adjust partner bot behavior to their personal preferences.

If you find specific examples of where the bot is doing this wrong, please still feel free to reactivate this issue and share them, but from what I can tell this is currently working as expected and aligns with generally available guidance.
