### ISSUE TITLE
Euchre: Limit alone in NT if not leading

### ISSUE THREAD

**Issue by antross** [TricksterCards/TricksterBots#228]
Currently the bot is getting Euchred on NT alone bids. NT bids are tricky if not the first to lead. 

Should fix by keeping partner in unless first to lead or all 4 suits are covered.

**Comment by johnson520** [comment]
> In Euchre, when a team is sitting on 8 or 9 the bots will often unnecessarily go alone. I consider it a violation of etiquette when all you need is 1 or 2 points to win the game. If you need 2 to win you should always take your partner with you. I recently had a bot partner go alone with 8 points and failed to make it when I had the needed card to take all the tricks. Please stop the bots from going alone with 8 or 9 points. Should only go alone with 7 or less points. Always.

**Comment by antross** [comment]
Fixed as part of #273
