### ISSUE TITLE
Spades: Comments on annoying tendencies with the bots

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#240]
> This is the best spades game I've found. Really enjoy it. I have found some annoying tendencies with the bots though. Not sure how hard they are to program, so I realize they may just be as good as they can be right now. Anyway, they tend to immediately start to throw all spades, which reduces my hand value if I needed my smaller spades. They also play with little care of bags. They just Win tricks and take as many bags as they take. Thanks for this chance to give feedback.

**Comment by antross** [comment]
This doesn't seem to match general bot behavior (especially the part of not caring about bags). May be specific to certain rules combinations but without concrete examples I don't think this issue is actionable. Closing.
