### ISSUE TITLE
Euchre: Protect the left (i.e., second-highest ranked trump)

### ISSUE THREAD

**Issue by drittich** [TricksterCards/TricksterBots#30]
I don't remembering observing this in-game, but from reading the code, it appears the logic in `SuggestNextCard` does not "protect the left" when the opponents are the makers. This can be a costly error, and is one of the first things new players learn, so feels like it should be standard practice in the bot.

There are various things to consider when implementing this that you may choose to ignore. E.g., you don't need to protect the second highest trump once the highest-ranked trump has been played (involves memory).

**Comment by antross** [comment]
Adding the comment from #34 where this was reported by another customer as well:

> When defending and the bot defender holds the left bower and another small trump, the bot will, when able, trump small leaving the left bower alone. I've been playing Euchre for over 60 years and the first thing you learn is to never bare your left bower. You will surely lose it and that is what happens in your game. You get over trumped and out comes the right bower. When my bot partner bares the left bower and then loses it giving the opponents 2 or 4 points instead of 1, I want to teach the bot but there is no way to do it except to write you. This happens very frequently. The only time to trump small is when you are last to play to the trick.
