### ISSUE TITLE
500: Suggestion for Bot Play Against Open Misère

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#33]
For what it's worth:

> Bot needs to only lead suits that bidder has shown in open misère & avoid any suits that are known that the bidder is void.

**Comment by antross** [comment]
> The AI algorithm when they play misere needs serious fixing. The computer short suits itself even though the card is there to be won (lower) on another suit.

> Eg I ensure I’ve short suited a suit then lead back to computer with another suit so they play a lower card under the short-suited suit. Eg play all my spades stayingnunder their king spades. Lead back a four diamonds so computer take lead knowing they have spades after calling it. They then play an off suit club to short suit themself due to the terrible algorithm, leading the opposition to get rid of the king spades. They then play a spade…please fix this in misere especially.

**Comment by antross** [comment]
> Bot had winning hand but didn't play it.
> 
> Opposition went Open Misère, I had run out of clubs a lot earlier, the bot kept playing other suit and high cards, when Nora (bot) could have played the 9CL then 5CL to win, which was clear after I received the claim and the cards held are displayed. Note that although it looks like the bot couldn't get the lead, it had the lead many times and didn't play the winning cards.
> 
> The bots are terrible at misère, especially open misère, often playing suits that the opposition don't have when they had an alternative.

**Comment by antross** [comment]
Customer provided this scenario he saw happen. "I" in this case is the player going Misère.

> Playing a misère hand, I led 6D, left seat 7D and right seat 5D – right seat LATER played Jack D which is the card that should have been discarded, preserving the 5…

**Comment by antross** [comment]
Dug into this a bit and it appears the current bot only uses the visible hand to look for void suits and doesn't look at the specific cards the Open Misere bidder is holding. This causes it to miss opportunities that are obvious to human players. We'll probably want special handling for this case to help the bot more effectively target an Open Misere bidder.

**Comment by antross** [comment]
> When the opponent calls misere and I’m playing with a bot it’s a garunteed loss, even when it could be an easy win, after the first round and the cards are revealed the bot always throws a card in a suit where the person playing the misere hand doesn’t have any of that suit, leading them to be able to dispose of any cards that could cause them to lose the hand.
