### ISSUE TITLE
Spades: Bid Nil more often in games with Nil passing

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#39]
A customer wrote:

> Maybe others have commented, but my feedback is about Spades. In 2-pass Nil games, if I get a hand with like 7 spades, some face cards, and a joker, I might not "have" 10, but I would bid 8-10 and hope that my partner bids Nil because that would score us way more points than my partner bidding one to my 8 or 9. But that's what I see very often, a lack of Nil bid from the bots. Only if the bots' own cards--in isolation--call for an easy Nil, then you see the Nil bid. If that makes sense?

My summary of this was:

> I can see two ways that our Spades bots could be improved for Nil bidding.
> 
> 1. Take into account the fact that they get to pass 2 cards to their partner
> 
> 2. Take into account the bid of their partner
> 
> I don't think they do either of these today. Am I correct in that's what your suggesting?

Their reply was "yes."

**Comment by antross** [comment]
> Why bot bid one on 2 card pass? If you only got one then bid nil and pass it

**Comment by antross** [comment]
We had another customer report an issue that appears to be due to this behavior over the weekend.

**Comment by johnson520** [comment]
> Please gear the bots to go Nil in the JJDD Spades game. The joker-joker-deuce-deuce game is a battle of the Nils. The bots bag too much and hardly ever go nil. You can start by not letting them bid 1,2,or 3. Have them bid Nil or 5+ more often. The bots truly do not know how to play this game.
