### ISSUE TITLE
Bridge: Play conventional first-card leads

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#47]
> the general practice of the game is to play second hand low and third hand high.

**Comment by johnson520** [comment]
From a customer:

> Opening lead should be changed
> 
> When NT is trump lead the longest suit not the shortest suit. Don't lead the Ace unless the hand also has the King. Lead a low card to setup the the upper cards.
> 
> When a suit is trump lead the shortest suit. Don't lead an Ace unless there is only two cards in the suit and after the Ace immediately lead the second card so the hand is then void in that suit.

**Comment by antross** [comment]
This has been fixed by our recent improvements to defensive play of the Bridge bots.
