### ISSUE TITLE
500: Don't bleed all trump from opponents

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#48]
From a customer:

> Have the computer stop leading trumps when there are only two or three out there, or when one opponent is void. Too often the bot keeps leading until all opponents are void, often draining more of their own and partner’s trumps than their opponents. This loses games!

**Comment by antross** [comment]
Not sure I agree with this particular feedback. Failing to bleed trump from the opponents gives them opportunities to take tricks they otherwise wouldn't have.
