### ISSUE TITLE
Bridge: Not always ruffing from 3rd/4th seat on defense

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#91]
We got positive feedback from the player who was sending the PBNs.

Here's feedback from someone else:

> Noticed a programming change were bots are “sitting” on cards to play later in hand. I’ve played a suit where I know the bot doesn’t have one to allow them to trump and they don’t play the trump. Then the opponent leads with Trump and takes their only Trump with a higher card. Dumb. Ned’s to be fixed. Play what is logical.

**Comment by antross** [comment]
The most recent comment sounds like the bot is choosing not to trump in from 3rd/4th seat which should only happen in a few rare cases. Worth a closer look to see if this might be happening more often than it should. 

@johnson520 a PBN of an example would be helpful here too if we can get one.

**Comment by johnson520** [comment]
Another from a different player:

> You have made the bridge bots defensive playing far worse than it was. There are so many guidelines as to what card you lead. Rarely is it a good idea to lead the opponents' trump suit. I groan every time my partner is a bot and they drain me of trump that I could have used elsewhere. It is almost as bad as their leading all their aces when playing no trump, thus allowing the other team to set up a long suit. I used to suffer through playing with a bot hoping I'd get a real person next round. Now I simply quit the game.
