### ISSUE TITLE
Pitch: 5-player 10-point: Bots don't play to set the bidder

### ISSUE THREAD

**Issue by johnson520** [TricksterCards/TricksterBots#98]
> I play 5 player 10 point a lot. Not that much of a challenge when the computer players do not play to set the bidder. It's as though they don't even know the card that is being called. They will play high cards that they should save to take tricks later. Also, I don't think the bidder should end up with the card that's being called.

**Comment by antross** [comment]
Fixed by 1661c90737e6495c66a8bf92025b1568fdf0cd06
